### ISSUE TITLE
Expicitar que é global

### ISSUE THREAD

**Issue by rafaelcorsi** [JoseFernandoInsper/provapratica#1]
https://github.com/JoseFernandoInsper/provapratica/blob/ace211b0392a577bda365de6d075a2b1f1805632/OLED-Xplained-Pro-SPI/src/main.c#L65-L68

variáveis globais são perigosas, você sempre deve explicitar que uma variável é global, exemplo:

```c
g_time
```

**Comment by JoseFernandoInsper** [comment]
done
