### ISSUE TITLE
padronizar true

### ISSUE THREAD

**Issue by rafaelcorsi** [JoseFernandoInsper/provapratica#4]
https://github.com/JoseFernandoInsper/provapratica/blob/ace211b0392a577bda365de6d075a2b1f1805632/OLED-Xplained-Pro-SPI/src/main.c#L170

tem momentos que você usa `1` para flag e outros `true`, tente padronizar um ou outro (preferência pelo `1`).

**Comment by JoseFernandoInsper** [comment]
done
