### ISSUE TITLE
parâmetro

### ISSUE THREAD

**Issue by rafaelcorsi** [JoseFernandoInsper/provapratica#5]
https://github.com/JoseFernandoInsper/provapratica/blob/ace211b0392a577bda365de6d075a2b1f1805632/OLED-Xplained-Pro-SPI/src/main.c#L102

já que você fez uma função para decrementar o tempo, ela poderia receber como parâmetro um ponteiro para a variável

```c
void TimerDec(uint *pTime){
 *pTime--;
}
```

**Comment by JoseFernandoInsper** [comment]
done
