### ISSUE TITLE
IRQ deve ser rápido

### ISSUE THREAD

**Issue by rafaelcorsi** [JoseFernandoInsper/provapratica#6]
https://github.com/JoseFernandoInsper/provapratica/blob/ace211b0392a577bda365de6d075a2b1f1805632/OLED-Xplained-Pro-SPI/src/main.c#L179

não atualizar o LCD em nenhuma IRQ, isso deve ser feito no main!!!

**Comment by JoseFernandoInsper** [comment]
done
