### ISSUE TITLE
init

### ISSUE THREAD

**Issue by rafaelcorsi** [JoseFernandoInsper/provapratica#8]
https://github.com/JoseFernandoInsper/provapratica/blob/ace211b0392a577bda365de6d075a2b1f1805632/OLED-Xplained-Pro-SPI/src/main.c#L291

porque não colocar toda iniciação dentro da função `init()`?

```c
	RTC_init();
	SW_init();
	LED_init(1);
	TC_init(TC0, ID_TC1, 1, 1);
```

**Comment by JoseFernandoInsper** [comment]
done
